apiVersion: batch/v1
kind: Job
metadata:
  name: rsatool
spec:
  template:
    metadata:
      name: rsa-crack-pod
    spec:
      containers:
      - name: rsacracktool
        image: mainrsacracking:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 1337
      restartPolicy: Never